# Generated by Django 3.2.9 on 2021-12-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(blank=True, upload_to='episodes')),
            ],
        ),
        migrations.RemoveField(
            model_name='seasons',
            name='videos',
        ),
        migrations.AddField(
            model_name='movies',
            name='video_file',
            field=models.FileField(blank=True, upload_to='movies'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='seasons',
            name='episodes',
            field=models.ManyToManyField(to='myapp.Episode'),
        ),
    ]
